---
name: HVAC IP MQTT Bridge
version: 0.0.1
slug: hvac_ip_mqtt_bridge
description: A bridge to connect between ip-enabled HVAC units and mqtt (to be connected to HomeAssistant etc)
url: https://github.com/PrimusNZ/addon-hvac-ip-mqtt-bridge
startup: application
arch:
  - armhf
  - amd64
  - i386
  - armv7
  - aarch64
hassio_api: true
init: false
services:
  - mqtt:need

#image: ghcr.io/primusnz/hassio-addons/{arch}-hvac-ip-mqtt-bridge
